version: "2"

services:
    feed-master:
        image: umputun/feed-master:master
        container_name: feed-master
        hostname: feed-master
        restart: always

        logging: &default_logging
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        networks:
            - proxy
            - default

        environment:
            - MHOST
            - DEBUG=false
            - FM_DB=/srv/var/feed-master.bdb
            - FM_CONF=/srv/etc/fm.yml
        volumes:
            - ./var:/srv/var # mapped location to save status
            - ./etc:/srv/etc # mapped location for config
        ports:
            - "8097:8080"

    fm-updater:
        build: updater
        hostname: fm-updater
        container_name: fm-updater
        restart: always
        logging: *default_logging
        volumes:
            - /home/umputun/.ssh/id_rsa.pub:/home/app/.ssh/id_rsa.pub
            - /home/umputun/.ssh/id_rsa:/home/app/.ssh/id_rsa

networks:
    proxy:
        external:
            name: nginx_proxy
